app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@AppBundle/Controller/"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/
